# Generated by Django 5.2.6 on 2025-09-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField()),
                ('url', models.URLField()),
                ('source', models.CharField(choices=[('news24', 'News24'), ('mybroadband', 'MyBroadband'), ('manual', 'Manual Entry')], max_length=20)),
                ('category', models.CharField(choices=[('ict', 'ICT'), ('solar', 'Solar & Power'), ('general', 'General')], max_length=10)),
                ('published_date', models.DateTimeField()),
                ('scraped_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-published_date'],
                'unique_together': {('title', 'source')},
            },
        ),
    ]
